version: '2'
services:
  web:
    image: nginx
    container_name: mentorship_cms_web
    ports:
      - "8181:81"
    volumes:
      - ./web:/var/www/html
      - ./conf.d:/etc/nginx/conf.d
    links:
      - php
    networks:
      - mentorship-cms
  php:
    container_name: mentorship_cms_php
    #image: php:7-fpm
    build:
      context: ./
      dockerfile: Dockerfile-phpfpm
    volumes:
      - ./web:/var/www/html
    networks:
      - mentorship-cms
    links:
      - db
    depends_on:
      - db
    expose:
      - 9000
  db:
    image: mysql:5.7
    container_name: mentorship_cms_db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms
    networks:
      - mentorship-cms
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: mentorship_cms_pma
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8184:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
    networks:
      - mentorship-cms
networks:
  mentorship-cms:
    driver: bridge
