home:
  path: /
  controller: App\Controller\HomeController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
  path: /logout  
  controller: App\Controller\SecurityController::logout
category:
  path: /category  
  controller: App\Controller\CategoryController::index
product:
  path: /product  
  controller: App\Controller\ProductController::index

    

