home:
  path: /
  controller: App\Controller\HomeController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
  path: /logout  
  controller: App\Controller\SecurityController::logout
category:
  path: /category  
  controller: App\Controller\CategoryController::index
product:
  path: /product  
  controller: App\Controller\ProductController::index
delete_product:
  path: /product/delete/{product}
  controller: App\Controller\ProductController::deleteAction
edit_product:
  path: /product/edit/{product}
  controller: App\Controller\ProductController::editAction
create_product: 
  path: /product/create
  controller: App\Controller\ProductController::createAction




